#!/usr/bin/env python3
"""
Build a single-page HTML book from git_3.0_astrosynthesis markdown files.

Outputs: book3/index.html
"""

import os
import re
from pathlib import Path
import markdown

BOOK_ROOT = Path("git_3.0_astrosynthesis/book")
OUTPUT_DIR = Path("book3")
OUTPUT_FILE = OUTPUT_DIR / "index.html"


def collect_files():
    """Collect all markdown files in reading order."""
    files = []

    # Title page / TOC
    idx = BOOK_ROOT / "index.md"
    if idx.exists():
        files.append(idx)

    # Preface
    preface = BOOK_ROOT / "00_preface" / "README.md"
    if preface.exists():
        files.append(preface)

    # Parts in alphabetical order (00_, part_i_, part_ii_, … sorts correctly)
    parts = sorted(
        [d for d in BOOK_ROOT.iterdir() if d.is_dir() and d.name.startswith("part_")]
    )
    for part in parts:
        part_readme = part / "README.md"
        if part_readme.exists():
            files.append(part_readme)

        chapters = sorted([d for d in part.iterdir() if d.is_dir()])
        for chapter in chapters:
            ch_readme = chapter / "README.md"
            if ch_readme.exists():
                files.append(ch_readme)

            sections = sorted([d for d in chapter.iterdir() if d.is_dir()])
            for section in sections:
                sec_readme = section / "README.md"
                if sec_readme.exists():
                    files.append(sec_readme)

    # Conclusion
    conclusion = BOOK_ROOT / "conclusion" / "README.md"
    if conclusion.exists():
        files.append(conclusion)

    # Appendices
    app_readme = BOOK_ROOT / "appendices" / "README.md"
    if app_readme.exists():
        files.append(app_readme)

    app_dir = BOOK_ROOT / "appendices"
    if app_dir.exists():
        app_files = sorted(
            [
                f
                for f in app_dir.iterdir()
                if f.suffix == ".md" and f.name != "README.md"
            ]
        )
        files.extend(app_files)

    return files


def read_and_fix(path: Path) -> str:
    """Read a markdown file and add a horizontal rule separator before h1 headings
    (except the very first file) so chapters visually break apart."""
    text = path.read_text(encoding="utf-8")
    # Normalize Windows line endings
    text = text.replace("\r\n", "\n")
    return text


def build_combined_markdown(files):
    """Concatenate all files with blank-line separators."""
    chunks = []
    for i, f in enumerate(files):
        content = read_and_fix(f)
        if i > 0:
            # Add a thematic break before each new file so the page flows
            chunks.append("\n\n---\n\n")
        chunks.append(content.strip())
    return "\n\n".join(chunks)


def md_to_html(combined_md: str) -> str:
    """Convert markdown to HTML using python-markdown with pymdownx extensions."""
    extensions = [
        "pymdownx.arithmatex",
        "pymdownx.superfences",
        "pymdownx.highlight",
        "pymdownx.inlinehilite",
        "pymdownx.smartsymbols",
        "tables",
        "toc",
        "attr_list",
        "def_list",
        "footnotes",
        "meta",
    ]
    extension_configs = {
        "pymdownx.arithmatex": {
            "generic": True,  # outputs \(...\) and \[...\] for MathJax
        },
        "pymdownx.highlight": {
            "anchor_linenums": False,
            "use_pygments": True,
            "guess_lang": False,
        },
        "toc": {
            "permalink": True,
            "toc_depth": 3,
        },
    }

    md = markdown.Markdown(
        extensions=extensions,
        extension_configs=extension_configs,
    )
    body_html = md.convert(combined_md)
    toc_html = md.toc  # generated by 'toc' extension
    return body_html, toc_html


HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Astrosynthesis 3.0 — The Complete Account</title>

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,300;0,400;0,600;1,300;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">

  <!-- MathJax — must be configured BEFORE the script loads -->
  <script>
    MathJax = {
      tex: {
        inlineMath:  [['\\\\(', '\\\\)']],
        displayMath: [['\\\\[', '\\\\]']],
        processEscapes: true,
        tags: 'ams'
      },
      options: {
        skipHtmlTags: ['script','noscript','style','textarea','pre','code']
      },
      startup: {
        ready() {
          MathJax.startup.defaultReady();
        }
      }
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script" async></script>

  <!-- Syntax highlighting (Pygments tomorrow-night theme via CDN fallback) -->
  <style>
    /* ── Reset & box-sizing ── */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    /* ── Colour tokens ── */
    :root {
      --bg:          #faf9f6;
      --fg:          #1c1b18;
      --fg-muted:    #5a5852;
      --accent:      #3d3a8c;
      --accent-lt:   #6660c8;
      --rule:        #d8d4c8;
      --code-bg:     #f3f1eb;
      --math-bg:     #f8f6ff;
      --toc-bg:      #f3f1eb;
      --toc-border:  #ccc8bc;
      --link:        #2c2980;
      --link-hover:  #5550b8;
      --max-w:       780px;
      --toc-w:       260px;
      --font-body:   'Crimson Pro', Georgia, 'Times New Roman', serif;
      --font-mono:   'JetBrains Mono', 'Courier New', monospace;
    }

    /* ── Layout ── */
    html { font-size: 18px; scroll-behavior: smooth; }

    body {
      background: var(--bg);
      color: var(--fg);
      font-family: var(--font-body);
      font-weight: 300;
      line-height: 1.75;
      display: flex;
      min-height: 100vh;
    }

    /* ── TOC sidebar ── */
    #toc-sidebar {
      position: fixed;
      top: 0;
      left: 0;
      width: var(--toc-w);
      height: 100vh;
      overflow-y: auto;
      background: var(--toc-bg);
      border-right: 1px solid var(--toc-border);
      padding: 1.4rem 1rem 2rem 1.2rem;
      font-size: 0.72rem;
      line-height: 1.5;
      z-index: 100;
    }

    #toc-sidebar h2 {
      font-size: 0.65rem;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: var(--fg-muted);
      margin-bottom: 0.8rem;
      border: none;
    }

    /* override toc extension list styles */
    #toc-sidebar ul { list-style: none; padding: 0; margin: 0; }
    #toc-sidebar li { padding: 0.08rem 0; }
    #toc-sidebar a {
      color: var(--fg-muted);
      text-decoration: none;
      display: block;
      padding: 0.06rem 0.25rem;
      border-radius: 2px;
      transition: color 0.15s, background 0.15s;
    }
    #toc-sidebar a:hover { color: var(--accent); background: rgba(61,58,140,0.06); }
    /* indent nested levels */
    #toc-sidebar ul ul { padding-left: 0.9rem; }
    #toc-sidebar ul ul ul { padding-left: 0.9rem; }

    /* ── Main content ── */
    #main {
      margin-left: var(--toc-w);
      max-width: calc(var(--toc-w) + var(--max-w) + 4rem);
      width: 100%;
    }

    #book-content {
      max-width: var(--max-w);
      margin: 0 auto;
      padding: 3.5rem 2rem 6rem;
    }

    /* ── TOC toggle (mobile) ── */
    #toc-toggle {
      display: none;
      position: fixed;
      top: 0.8rem;
      left: 0.8rem;
      z-index: 200;
      background: var(--accent);
      color: #fff;
      border: none;
      padding: 0.35rem 0.7rem;
      border-radius: 4px;
      font-size: 0.8rem;
      cursor: pointer;
    }

    /* ── Typography ── */

    /* Headings */
    h1, h2, h3, h4, h5, h6 {
      font-family: var(--font-body);
      font-weight: 600;
      color: var(--fg);
      line-height: 1.25;
      margin-top: 2.4rem;
      margin-bottom: 0.7rem;
    }

    h1 {
      font-size: 1.9rem;
      border-bottom: 2px solid var(--accent);
      padding-bottom: 0.35rem;
      margin-top: 3rem;
    }

    h2 {
      font-size: 1.4rem;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 0.2rem;
    }

    h3 { font-size: 1.15rem; }
    h4 { font-size: 1rem; color: var(--fg-muted); }

    /* First h1 of the whole page is the book title */
    #book-content > h1:first-child {
      font-size: 2.4rem;
      text-align: center;
      border-bottom: 3px solid var(--accent);
      padding-bottom: 0.5rem;
      margin-top: 0;
    }

    /* Paragraph */
    p { margin-bottom: 1rem; }

    /* Links */
    a { color: var(--link); text-decoration: underline; text-underline-offset: 2px; }
    a:hover { color: var(--link-hover); }

    /* Emphasis */
    strong { font-weight: 600; }
    em { font-style: italic; }

    /* Horizontal rules become chapter dividers */
    hr {
      border: none;
      border-top: 1px solid var(--rule);
      margin: 3.5rem 0;
      position: relative;
    }
    hr::after {
      content: "✦";
      position: absolute;
      top: -0.7em;
      left: 50%;
      transform: translateX(-50%);
      background: var(--bg);
      padding: 0 0.5rem;
      color: var(--rule);
      font-size: 0.8rem;
    }

    /* ── Lists ── */
    ul, ol { margin: 0.6rem 0 1rem 1.6rem; }
    li { margin-bottom: 0.25rem; }
    li > p { margin-bottom: 0.3rem; }

    /* Definition lists */
    dl { margin-bottom: 1rem; }
    dt { font-weight: 600; margin-top: 0.6rem; }
    dd { margin-left: 1.5rem; }

    /* ── Block math ── */
    .arithmatex.block-math,
    mjx-container[display="true"] {
      display: block;
      overflow-x: auto;
      background: var(--math-bg);
      border-left: 3px solid var(--accent-lt);
      padding: 0.8rem 1rem;
      margin: 1.2rem 0;
      border-radius: 0 4px 4px 0;
    }

    /* ── Inline math ── */
    mjx-container[display="false"] {
      font-size: 1em !important;
    }

    /* ── Code ── */
    code {
      font-family: var(--font-mono);
      font-size: 0.82em;
      background: var(--code-bg);
      border: 1px solid var(--rule);
      border-radius: 3px;
      padding: 0.1em 0.35em;
    }

    pre {
      background: #1e1e2e;
      color: #cdd6f4;
      border-radius: 6px;
      padding: 1.1rem 1.3rem;
      overflow-x: auto;
      margin: 1.2rem 0;
      font-size: 0.8rem;
      line-height: 1.55;
    }

    pre code {
      background: none;
      border: none;
      padding: 0;
      color: inherit;
      font-size: inherit;
    }

    /* ── Tables ── */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1.2rem 0;
      font-size: 0.88rem;
    }

    th {
      background: var(--accent);
      color: #fff;
      padding: 0.5rem 0.8rem;
      text-align: left;
      font-weight: 600;
    }

    td {
      padding: 0.4rem 0.8rem;
      border-bottom: 1px solid var(--rule);
    }

    tr:nth-child(even) td { background: #f5f3ef; }

    /* ── Blockquotes ── */
    blockquote {
      border-left: 4px solid var(--accent-lt);
      padding: 0.5rem 1rem;
      margin: 1rem 0;
      color: var(--fg-muted);
      background: #f8f6ff;
      border-radius: 0 4px 4px 0;
    }

    blockquote p { margin-bottom: 0; }

    /* ── Footnotes ── */
    .footnote { font-size: 0.82rem; color: var(--fg-muted); }
    .footnote ol { margin-left: 1rem; }

    /* ── Anchor links from TOC extension ── */
    .headerlink {
      opacity: 0;
      font-size: 0.75em;
      color: var(--accent-lt);
      text-decoration: none;
      margin-left: 0.4em;
      transition: opacity 0.2s;
    }
    h1:hover .headerlink,
    h2:hover .headerlink,
    h3:hover .headerlink { opacity: 1; }

    /* ── Responsive: hide TOC on narrow screens ── */
    @media (max-width: 900px) {
      #toc-toggle { display: block; }
      #toc-sidebar {
        transform: translateX(-100%);
        transition: transform 0.25s ease;
      }
      #toc-sidebar.open { transform: translateX(0); }
      #main { margin-left: 0; }
      #book-content { padding: 1.5rem 1rem 4rem; }
    }

    /* ── Print styles ── */
    @media print {
      #toc-sidebar, #toc-toggle { display: none !important; }
      #main { margin-left: 0; }
      #book-content { max-width: 100%; padding: 0; }
      hr { page-break-after: always; }
    }
  </style>
</head>
<body>

<button id="toc-toggle" aria-label="Toggle table of contents">☰ Contents</button>

<nav id="toc-sidebar" aria-label="Table of contents">
  <h2>Contents</h2>
  {TOC}
</nav>

<div id="main">
  <article id="book-content">
    {BODY}
  </article>
</div>

<script>
  // Mobile TOC toggle
  const btn = document.getElementById('toc-toggle');
  const toc = document.getElementById('toc-sidebar');
  btn.addEventListener('click', () => toc.classList.toggle('open'));

  // Close TOC when a link inside it is clicked (mobile)
  toc.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => {
      if (window.innerWidth <= 900) toc.classList.remove('open');
    });
  });
</script>

</body>
</html>
"""


def main():
    print("Collecting markdown files…")
    files = collect_files()
    print(f"  Found {len(files)} files")

    print("Combining markdown…")
    combined = build_combined_markdown(files)

    print("Converting to HTML…")
    body_html, toc_html = md_to_html(combined)

    print("Writing output…")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    html = HTML_TEMPLATE.replace("{BODY}", body_html).replace("{TOC}", toc_html)
    OUTPUT_FILE.write_text(html, encoding="utf-8")

    size_kb = OUTPUT_FILE.stat().st_size // 1024
    print(f"  Written: {OUTPUT_FILE}  ({size_kb} KB)")
    print("Done.")


if __name__ == "__main__":
    main()
